name: Action Detect Version
description: get version information from under the specified directory
author: ShotaKitazawa
inputs:
  pr_url:
    description: value of github.event.pull_request.url
    required: true
  dir:
    description: specified directory path enumerated folder that it was named of version information
    required: true
outputs:
  new_version:
    description: A semver update level ({major, minor, patch}).
runs:
  using: docker
  image: Dockerfile
branding:
  icon: paperclip
  color: blue

